name: CI

on:
  push:
    branches:
      - master
    tags-ignore:
      - v*
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build the Binary Files
    runs-on: ubuntu-latest
    env:
      DEBIAN_FRONTEND: noninteractive
      USE_CHOICE: x86_64
    steps:
    - name: Clone Current Repository
      uses: actions/checkout@master
    - name: Install Dependencies
      run: |
        sudo -E apt-get update
        sudo -E apt-get -y install flex gawk git jq wget
    - name: Initialize Environment
      run: |
        USE_BRANCH=$(jq -r .qbt.USE_BRANCH dynamic.json)
        vars="USE_PROTOCOL USE_DOMAIN USE_RELEASE USE_VERSION"
        for i in $vars; do
          eval "${i}=$(jq -r .openwrt.${i} dynamic.json)"
        done

        vars="USE_GCC USE_TARGET USE_SUBTARGET USE_UNIQUE USE_EABI"
        for i in $vars; do
          eval "${i}=$(jq -r .openwrt[\"${{env.USE_CHOICE}}\"].${i} dynamic.json)"
        done

        USE_SOURCE_URL=${USE_PROTOCOL}://${USE_DOMAIN}/${USE_RELEASE}
        SDK_FILE=openwrt-sdk

        [ "${USE_RELEASE}" = "releases" ] && {
          USE_SOURCE_URL=${USE_SOURCE_URL}/${USE_VERSION}
          SDK_FILE=${SDK_FILE}-${USE_VERSION}
        }

        SDK_FILE=${SDK_FILE}-${USE_TARGET}
        [ "${USE_UNIQUE}" = "1" ] || SDK_FILE="${SDK_FILE}-${USE_SUBTARGET}"

        SDK_FILE=${SDK_FILE}_${USE_GCC}
        [ "${USE_EABI}" = "1" ] && SDK_FILE="${SDK_FILE}_eabi"

        SDK_FILE=${SDK_FILE}.Linux-x86_64.tar.xz
        USE_SOURCE_URL=${USE_SOURCE_URL}/targets/${USE_TARGET}/${USE_SUBTARGET}

        echo "USE_BRANCH=${USE_BRANCH}" >> $GITHUB_ENV
        echo "USE_TARGET=${USE_TARGET}" >> $GITHUB_ENV
        echo "USE_SUBTARGET=${USE_SUBTARGET}" >> $GITHUB_ENV
        echo "USE_SOURCE_URL=${USE_SOURCE_URL}" >> $GITHUB_ENV
        echo "USE_SDK_FILE=${SDK_FILE}" >> $GITHUB_ENV
    - name: Check Version
      run: |
        curl -O "${{env.USE_SOURCE_URL}}/version.buildinfo"
        curl -O "${{env.USE_SOURCE_URL}}/feeds.buildinfo"
        [ -e "version.buildinfo" ] && version="$(echo $(cat version.buildinfo))" || version="${{ github.run_id }}"
        [ -e "feeds.buildinfo" ] && feeds="$(echo $(md5sum feeds.buildinfo | cut -d ' ' -f 1))" || feeds="${{ github.run_id }}"
        echo "USE_SDK_VERSION=${version}" >> $GITHUB_ENV
        echo "USE_FEEDS_VERSION=${feeds}" >> $GITHUB_ENV
    - name: Cache SDK
      uses: actions/cache@v2.1.5
      id: cache-sdk
      with:
        path: ./${{ env.USE_SDK_FILE }}
        key: SDK-${{env.USE_CHOICE}}-${{ env.USE_SDK_VERSION }}
    - if: steps.cache-sdk.outputs.cache-hit != 'true'
      run: |
        wget --no-check-certificate ${{ env.USE_SOURCE_URL }}/${{ env.USE_SDK_FILE }}
    - run: |
        tar -xJf ${{ env.USE_SDK_FILE }}
        find ./ -maxdepth 1 -type d -iname 'openwrt-sdk*' -exec mv {} build \;
        rm -rf build/dl build/feeds
    - name: Cache Source
      uses: actions/cache@v2.1.5
      with:
        path: |
          build/dl
          build/feeds
        key: source-dynamic-${{ env.USE_FEEDS_VERSION }}
        restore-keys: |
          source-dynamic-
          source-
    - name: Clone Source
      uses: actions/checkout@master
      with:
        ref: ${{env.USE_BRANCH}}
        repository: brvphoenix/SomePackages
        token: ${{ secrets.SUPER_TOKEN }}
        path: SomePackages
